# Shark Attack Project

`
    How

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import re
import pandas as pd
import os
from progressbar import ProgressBar
from tqdm import tqdm

In [2]:
#!pip install progressbar

In [3]:
os.chdir(r'C:\Users\bruna\IronHack\GitHub\Project\Project-2')

In [4]:
data=pd.read_csv('attacks.csv', encoding = 'latin1')

In [5]:
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [6]:
data.shape

(25723, 24)

In [7]:
null_cols = data.isnull().sum()

null_cols

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [8]:
null_perc = round(null_cols[null_cols > 0]/data.shape[0]*100, 2)
null_perc

Case Number                66.17
Date                       75.50
Year                       75.51
Type                       75.52
Country                    75.69
Area                       77.27
Location                   77.60
Activity                   77.62
Name                       76.32
Sex                        77.70
Age                        86.51
Injury                     75.61
Fatal (Y/N)                77.60
Time                       88.54
Species                    86.53
Investigator or Source     75.57
pdf                        75.50
href formula               75.50
href                       75.50
Case Number.1              75.50
Case Number.2              75.50
original order             75.47
Unnamed: 22               100.00
Unnamed: 23                99.99
dtype: float64

In [9]:
drop_cols = null_perc[null_perc>=80].index
drop_cols

Index(['Age', 'Time', 'Species ', 'Unnamed: 22', 'Unnamed: 23'], dtype='object')

In [10]:
data = data.drop(drop_cols, axis=1)
data.shape

(25723, 19)

In [11]:

data.isnull().sum()

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Injury                    19449
Fatal (Y/N)               19960
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
dtype: int64

In [12]:
fill_cols = data.columns[data.isna().sum()>0]

fill_cols

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Injury', 'Fatal (Y/N)',
       'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [13]:
data = data.iloc[:,1:].dropna()

In [14]:
data.columns

Index(['Date', 'Year', 'Type', 'Country', 'Area', 'Location', 'Activity',
       'Name', 'Sex ', 'Injury', 'Fatal (Y/N)', 'Investigator or Source',
       'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2',
       'original order'],
      dtype='object')

In [15]:
data.drop(['Investigator or Source', 'pdf', 
           'href formula', 'href', 'Case Number.1', 'Case Number.2',
          'Name', 'original order'], axis = 1, inplace=True)

In [16]:
data

,Date,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N)
0,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N
1,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N
2,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N
3,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N
4,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N
...,...,...,...,...,...,...,...,...,...,...
6290,Before 19-Jul-1913,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y
6296,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,M,FATAL,Y
6297,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,M,FATAL,Y
6299,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,FATAL,Y
6301,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,"FATAL. ""Shark bit him in half, carrying away t...",Y

In [17]:
data.isnull().sum()

Date           0
Year           0
Type           0
Country        0
Area           0
Location       0
Activity       0
Sex            0
Injury         0
Fatal (Y/N)    0
dtype: int64

In [18]:
data.Date = data.Date.astype(str)

In [19]:
pbar = ProgressBar()

In [20]:
dates = []
for row in pbar(data['Date']):
    d = ''.join(re.findall("[A-Za-z]{3}-[0-9]{4}", row))  
    if not d:
        d = np.nan
    dates.append(d)

100% |########################################################################|

In [21]:
data['Date'] = dates

In [22]:
data

,Date,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N)
0,Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N
1,Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N
2,Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N
3,Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N
4,Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N
...,...,...,...,...,...,...,...,...,...,...
6290,Jul-1913,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y
6296,NaN,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,M,FATAL,Y
6297,NaN,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,M,FATAL,Y
6299,NaN,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,FATAL,Y
6301,NaN,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,"FATAL. ""Shark bit him in half, carrying away t...",Y

In [23]:
data.dropna(inplace=True)

In [24]:
data

,Date,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N)
0,Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N
1,Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N
2,Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N
3,Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N
4,Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N
...,...,...,...,...,...,...,...,...,...,...
6231,May-1965,0.0,Unprovoked,GREECE,Island of Volos,Eastern shore,Swimming,F,FATAL,Y
6246,Apr-1959,0.0,Unprovoked,BERMUDA,Paget,Paget Parish,Spearfishing,M,Shoulder abraded by skin of shark,N
6288,Jul-1916,0.0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,"""Lost leg""",N
6289,Jul-1913,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,M,"FATAL, body not recovered but shark was caught...",Y
6290,Jul-1913,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y

In [25]:
data['Year'] = data.Date.str.split('-').str.get(-1)

In [26]:
data['Date'] = data.Date.str.split('-').str.get(0)

In [27]:
data.rename(columns={'Date':'Month'}, inplace=True)

In [28]:
data.head(30)

,Month,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N)
0,Jun,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N
1,Jun,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N
2,Jun,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N
3,Jun,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N
4,Jun,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N
5,Jun,2018,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,M,"No injury, board bitten",N
6,Jun,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,FATAL,Y
7,May,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,Minor injury to foot. PROVOKED INCIDENT,N
8,May,2018,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,Lower left leg bitten,N
9,May,2018,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,M,Minor injury to foot,N
10,May,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,Minor bite to hand by captive shark. PROVOKED ...,N
11,May,2018,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,M,Injuries to lower right leg and foot,N
12,May,2018,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,M,Severe bite to right forearm,N
13,May,2018,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,M,Injured by teeth of a dead porbeagle shark he ...,N
15,May,2018,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,M,"Minor injury, marks on board",N
16,May,2018,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,M,"No injury, surfboard damaged",N
17,Apr,2018,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,M,Minor injury to ankle,N
18,Apr,2018,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,M,"No injury, shark bit scuba gear",N
19,Apr,2018,Unprovoked,AUSTRALIA,Western Australia,Gearys Beach,Surfing,M,"No injury, knocked off board by shark",N
20,Apr,2018,Questionable,AUSTRALIA,New South Wales,Lennox Head,Surfing,M,No injury,N
21,Apr,2018,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,M,"No injury, knocked off board by shark",N
22,Apr,2018,Unprovoked,AUSTRALIA,Western Australia,"South Point, Gracetown",Surfing,M,"No injury, shark struck his leg",N
23,Apr,2018,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,M,5-inch cut to hand,N
24,Apr,2018,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,M,"No injury, shark bit hole in ski",N
25,Apr,2018,Unprovoked,USA,Hawaii,"Shipwrecks Beach, Keoneloa Bay, Kauai",Body boarding,M,Lacerations to right lower leg,N
26,Apr,2018,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,M,Lacerations to foot and ankle,N
28,Apr,2018,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,M,Laceration to right thigh,N
29,Apr,2018,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,M,Lacerations to legs,N
30,Apr,2018,Unprovoked,BAHAMAS,New Providence,Nirvana Beach,Surfing,M,No Injury. Shark swam away with the surf board,N
31,Apr,2018,Invalid,BRAZIL,Alagoas,"Praia de Sauaçuhy, Maceió",Fishing,M,Injury to ankle from marine animal trapped in ...,N

In [29]:
data['Country'].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'ECUADOR',
       'MALAYSIA', 'CUBA', 'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'REUNION', 'PHILIPPINES', 'INDONESIA',
       'FRENCH POLYNESIA', 'NEW CALEDONIA', 'DOMINICAN REPUBLIC',
       'MOZAMBIQUE', 'FRANCE', 'ISRAEL', 'JAMAICA', 'NIGERIA', 'TONGA',
       'SCOTLAND', 'ITALY', 'CHILE', 'TAIWAN', 'PAPUA NEW GUINEA',
       'RUSSIA', 'SEYCHELLES', 'COLUMBIA', 'TURKS & CAICOS', 'FIJI',
       'SOUTH KOREA', 'VIETNAM', 'MADAGASCAR',
       'UNITED ARAB EMIRATES (UAE)', 'PANAMA', 'SOLOMON ISLANDS', 'KENYA',
       'GUAM', 'CROATIA', 'NORWAY', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'CHINA', 'VANUATU', 'MEXICO ', ' TONGA', 'URUGUAY',
       'VENEZUELA', 'INDIA', 'MICRONESIA', 'CANADA', 'OKINAWA',
       'MARSHALL ISLANDS', 'SENEGAL', 'EGYPT / ISRAEL', 'HONG KONG',
       'SOMALIA', 'EL SALVADOR', 'NAMIBIA', 'PORTUGAL', 'WESTERN SAMOA',
       'BRITISH ISLES', 'PALAU', 'GRENADA', 'BERMUDA', 'TURKEY',
       'NEW BRITAIN', 'PACIFIC OCEAN ', 'NEW GUINEA',
       'FEDERATED STATES OF MICRONESIA', 'GREECE', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'NORTH PACIFIC OCEAN',
       'NORTH SEA', 'AMERICAN SAMOA', 'PACIFIC OCEAN', 'GABON', 'MALTA',
       'MONTENEGRO', 'YEMEN', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'IRAN', 'SUDAN', 'SAUDI ARABIA', 'TANZANIA', 'IRAQ', 'CAPE VERDE',
       'NICARAGUA', 'GUYANA', 'BARBADOS', 'HAITI', 'SAN DOMINGO', 'SAMOA',
       'CYPRUS', 'LIBYA', 'EGYPT ', 'YEMEN ', 'BURMA',
       'BRITISH NEW GUINEA', 'SIERRA LEONE', 'HONDURAS', 'KIRIBATI',
       'SRI LANKA', 'GUINEA', 'TASMAN SEA', 'KOREA'], dtype=object)

In [30]:
data.Country = data.Country.str.rstrip('?')

In [31]:
data

,Month,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N)
0,Jun,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N
1,Jun,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N
2,Jun,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N
3,Jun,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N
4,Jun,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N
...,...,...,...,...,...,...,...,...,...,...
6231,May,1965,Unprovoked,GREECE,Island of Volos,Eastern shore,Swimming,F,FATAL,Y
6246,Apr,1959,Unprovoked,BERMUDA,Paget,Paget Parish,Spearfishing,M,Shoulder abraded by skin of shark,N
6288,Jul,1916,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,"""Lost leg""",N
6289,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,M,"FATAL, body not recovered but shark was caught...",Y
6290,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y

In [32]:
len(data.Country.unique())

123

In [33]:
data.Country = data.Country.str.strip(' ')

In [34]:
len(data.Country.unique())

118

In [35]:
data.Country = data.Country.str.replace(r'[(][A-Z]{3}[)]', '')

In [36]:
len(data.Country.unique())

118

In [37]:
data.Country.unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'ECUADOR',
       'MALAYSIA', 'CUBA', 'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'REUNION', 'PHILIPPINES', 'INDONESIA',
       'FRENCH POLYNESIA', 'NEW CALEDONIA', 'DOMINICAN REPUBLIC',
       'MOZAMBIQUE', 'FRANCE', 'ISRAEL', 'JAMAICA', 'NIGERIA', 'TONGA',
       'SCOTLAND', 'ITALY', 'CHILE', 'TAIWAN', 'PAPUA NEW GUINEA',
       'RUSSIA', 'SEYCHELLES', 'COLUMBIA', 'TURKS & CAICOS', 'FIJI',
       'SOUTH KOREA', 'VIETNAM', 'MADAGASCAR', 'UNITED ARAB EMIRATES ',
       'PANAMA', 'SOLOMON ISLANDS', 'KENYA', 'GUAM', 'CROATIA', 'NORWAY',
       'Sierra Leone', 'ST. MAARTIN', 'GRAND CAYMAN', 'CHINA', 'VANUATU',
       'URUGUAY', 'VENEZUELA', 'INDIA', 'MICRONESIA', 'CANADA', 'OKINAWA',
       'MARSHALL ISLANDS', 'SENEGAL', 'EGYPT / ISRAEL', 'HONG KONG',
       'SOMALIA', 'EL SALVADOR', 'NAMIBIA', 'PORTUGAL', 'WESTERN SAMOA',
       'BRITISH ISLES', 'PALAU', 'GRENADA', 'BERMUDA', 'TURKEY',
       'NEW BRITAIN', 'PACIFIC OCEAN', 'NEW GUINEA',
       'FEDERATED STATES OF MICRONESIA', 'GREECE', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'NORTH PACIFIC OCEAN',
       'NORTH SEA', 'AMERICAN SAMOA', 'GABON', 'MALTA', 'MONTENEGRO',
       'YEMEN', 'THE BALKANS', 'SUDAN', 'ARGENTINA', 'IRAN',
       'SAUDI ARABIA', 'TANZANIA', 'IRAQ', 'CAPE VERDE', 'NICARAGUA',
       'GUYANA', 'BARBADOS', 'HAITI', 'SAN DOMINGO', 'SAMOA', 'CYPRUS',
       'LIBYA', 'BURMA', 'BRITISH NEW GUINEA', 'SIERRA LEONE', 'HONDURAS',
       'KIRIBATI', 'SRI LANKA', 'GUINEA', 'TASMAN SEA', 'KOREA'],
      dtype=object)

In [38]:
data.Country = data.Country.str.split(',').str.get(0)

In [39]:
data.Country.unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'ECUADOR',
       'MALAYSIA', 'CUBA', 'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'JAPAN',
       'EGYPT', 'ST HELENA', 'UNITED KINGDOM', 'UNITED ARAB EMIRATES',
       'REUNION', 'PHILIPPINES', 'INDONESIA', 'FRENCH POLYNESIA',
       'NEW CALEDONIA', 'DOMINICAN REPUBLIC', 'MOZAMBIQUE', 'FRANCE',
       'ISRAEL', 'JAMAICA', 'NIGERIA', 'TONGA', 'SCOTLAND', 'ITALY',
       'CHILE', 'TAIWAN', 'PAPUA NEW GUINEA', 'RUSSIA', 'SEYCHELLES',
       'COLUMBIA', 'TURKS & CAICOS', 'FIJI', 'SOUTH KOREA', 'VIETNAM',
       'MADAGASCAR', 'UNITED ARAB EMIRATES ', 'PANAMA', 'SOLOMON ISLANDS',
       'KENYA', 'GUAM', 'CROATIA', 'NORWAY', 'Sierra Leone',
       'ST. MAARTIN', 'GRAND CAYMAN', 'CHINA', 'VANUATU', 'URUGUAY',
       'VENEZUELA', 'INDIA', 'MICRONESIA', 'CANADA', 'OKINAWA',
       'MARSHALL ISLANDS', 'SENEGAL', 'EGYPT / ISRAEL', 'HONG KONG',
       'SOMALIA', 'EL SALVADOR', 'NAMIBIA', 'PORTUGAL', 'WESTERN SAMOA',
       'BRITISH ISLES', 'PALAU', 'GRENADA', 'BERMUDA', 'TURKEY',
       'NEW BRITAIN', 'PACIFIC OCEAN', 'NEW GUINEA',
       'FEDERATED STATES OF MICRONESIA', 'GREECE', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'NORTH PACIFIC OCEAN',
       'NORTH SEA', 'AMERICAN SAMOA', 'GABON', 'MALTA', 'MONTENEGRO',
       'YEMEN', 'THE BALKANS', 'SUDAN', 'ARGENTINA', 'IRAN',
       'SAUDI ARABIA', 'TANZANIA', 'IRAQ', 'CAPE VERDE', 'NICARAGUA',
       'GUYANA', 'BARBADOS', 'HAITI', 'SAN DOMINGO', 'SAMOA', 'CYPRUS',
       'LIBYA', 'BURMA', 'BRITISH NEW GUINEA', 'SIERRA LEONE', 'HONDURAS',
       'KIRIBATI', 'SRI LANKA', 'GUINEA', 'TASMAN SEA', 'KOREA'],
      dtype=object)

In [40]:
data.Country = data.Country.str.replace(r'^.*?/ ', '')

In [41]:
len(data.Country.unique())

117

In [42]:
data.Country.unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'ECUADOR',
       'MALAYSIA', 'CUBA', 'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'JAPAN',
       'EGYPT', 'ST HELENA', 'UNITED KINGDOM', 'UNITED ARAB EMIRATES',
       'REUNION', 'PHILIPPINES', 'INDONESIA', 'FRENCH POLYNESIA',
       'NEW CALEDONIA', 'DOMINICAN REPUBLIC', 'MOZAMBIQUE', 'FRANCE',
       'ISRAEL', 'JAMAICA', 'NIGERIA', 'TONGA', 'SCOTLAND', 'ITALY',
       'CHILE', 'TAIWAN', 'PAPUA NEW GUINEA', 'RUSSIA', 'SEYCHELLES',
       'COLUMBIA', 'TURKS & CAICOS', 'FIJI', 'SOUTH KOREA', 'VIETNAM',
       'MADAGASCAR', 'UNITED ARAB EMIRATES ', 'PANAMA', 'SOLOMON ISLANDS',
       'KENYA', 'GUAM', 'CROATIA', 'NORWAY', 'Sierra Leone',
       'ST. MAARTIN', 'GRAND CAYMAN', 'CHINA', 'VANUATU', 'URUGUAY',
       'VENEZUELA', 'INDIA', 'MICRONESIA', 'CANADA', 'OKINAWA',
       'MARSHALL ISLANDS', 'SENEGAL', 'HONG KONG', 'SOMALIA',
       'EL SALVADOR', 'NAMIBIA', 'PORTUGAL', 'WESTERN SAMOA',
       'BRITISH ISLES', 'PALAU', 'GRENADA', 'BERMUDA', 'TURKEY',
       'NEW BRITAIN', 'PACIFIC OCEAN', 'NEW GUINEA',
       'FEDERATED STATES OF MICRONESIA', 'GREECE', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'NORTH PACIFIC OCEAN',
       'NORTH SEA', 'AMERICAN SAMOA', 'GABON', 'MALTA', 'MONTENEGRO',
       'YEMEN', 'THE BALKANS', 'SUDAN', 'ARGENTINA', 'IRAN',
       'SAUDI ARABIA', 'TANZANIA', 'IRAQ', 'CAPE VERDE', 'NICARAGUA',
       'GUYANA', 'BARBADOS', 'HAITI', 'SAN DOMINGO', 'SAMOA', 'CYPRUS',
       'LIBYA', 'BURMA', 'BRITISH NEW GUINEA', 'SIERRA LEONE', 'HONDURAS',
       'KIRIBATI', 'SRI LANKA', 'GUINEA', 'TASMAN SEA', 'KOREA'],
      dtype=object)

In [43]:
data.Area = data.Area.str.replace(r'\([^()]*\)', '')

In [44]:
len(data.Area.unique())

502

In [45]:
data.Area.unique()

array(['California', 'Georgia', 'Hawaii', 'New South Wales', 'Colima',
       'Pernambuco', 'Florida', 'Queensland', 'South Carolina',
       'Cornwall', 'Eastern Cape Province', 'Hua Hin', 'Cocos Island',
       'Western Australia', 'Alifu Alifu Atoll', 'Western Cape Province',
       'New Providence', 'Alagoas', 'Victoria', 'KwaZulu-Natal',
       'Boi Island, Victoria', 'Galapagos Islands', 'Fernando de Noronha',
       'Sepang', 'Holquin Province', 'Pamplemousses ', 'South Australia',
       'North Island', 'Canary Islands', 'Westerm Australia',
       'Shizuoka Prefecture', 'Texas', 'Massachusetts',
       'Red Sea Protectorate', 'New Providence District',
       'Ascension Island', 'Majorca', 'Washington', 'Tabasco',
       'Ibiza Island', 'South Devon', 'New Providence ', 'Sharjah, ',
       'Baja California Sur', 'Saint-Leu', 'South Island', 'Luzon Island',
       'Bali', 'Tuamotos', 'Oregon', 'North Province',
       'New Providence Island', 'Alicante Province', 'Kochi Prefecture',
       'Tasmania', 'Abaco Islands', 'North Carolina', 'Suez',
       'Grand Terre', 'Santa Catarina State', 'South Province',
       'Altagracia Province', 'Balneário Camboriú', 'Fujairah Emirate',
       'Grand Canary Island', 'Inhambane Province', 'Phuket',
       'Guanacaste', 'Grand Bahama Island', 'Le Port', 'Rangiroa',
       'Saint-Gilles-les-Bains', 'Bora Bora', 'Sinaloa',
       'Central Tuamotu', 'd\x92Étang-Salé', 'Granada', 'Moorea',
       'Alabama', 'Catalonia', 'Maryland', 'Alicante', 'Louisiana',
       'Delaware', 'Atsumi peninsula', 'Wallis and Futuna',
       'Society Islands', 'Okinawa Prefecture', 'New Jersey',
       'Southern District', 'Exuma Islands', 'Saint-Paul',
       'Santa Cruz Island', 'Saint-Gilles', 'Quintana Roo', 'Tuamotus',
       'Eleuthera', 'St. Catherine', 'Palawan', 'Mercury Islands',
       'Delta', "Vava'u", 'Inner Hebrides', 'Sardinia', 'Guerrero',
       'Saint-Benoit', 'Antofagasta Province', 'Taitung ', 'Santa Elena',
       'East New Britain', 'Bois-Blanc ', 'Moray', 'Samaná Province',
       'Central Province', 'Primorsky Krai',
       'Peter the Great Bay, Khasan, Primorsky Krai ',
       'Telyakovsky Bay, Khasan,  Primorsky Krai ', 'Praslin', 'Sucre',
       'Middle Caicos', 'Caicos Bank', 'San Andrés archipelago', 'Kedah',
       'Vitu Levu', ' Loyalty Islands', 'Saint Gilles ', 'West End',
       'South Sinai Peninsula', 'Maine', 'Virginia', 'Jeju Province',
       'New York', 'Binh Dinh Province', 'Antsiranana Province',
       'Sinai Peninsula', 'Off Vanua Levu', 'Rio Grande Do Sul', 'Dubai',
       'Western Province', 'Torres Strait', 'Eastern Province',
       'Eastern Cape  Province', 'Maputo Province', 'Bocas', 'Fife',
       'Devon', 'Makira-Ulawa Province', 'Mombasa', 'St. Johns Reef',
       'Off Green Island', 'North Region', 'Batangas province',
       'Strait of Malacca', 'Puerto Rico', 'Guantanamo Province',
       'Red Sea', 'Batanes Provine', 'Luzon', 'Northern Territory',
       ' Split-Dalmatia Count,', 'North Devon', 'US Virgin Islands',
       'San Carlos', 'Sussex', 'Bahia', 'Guerro', 'Yasawa Islands',
       'Northern Bahamas', 'Baja California', 'Loyalty Islands',
       'Marovo Lagoon', 'Territory of Cocos  Islands', 'Oslo Fjord',
       'Kent', 'Cook islans', 'Saint-Pierre', 'Andros Islands', 'Guam',
       'Western Area', 'Simpson Bay', 'East Wall', 'Shanghai',
       'Malampa Province', "South Ch'ungch'ong Province", 'New Mexico',
       'Santiago de Cuba Province', 'Camaguey Province',
       'Conservatória District', 'South Carolina ',
       'Kuril Islands in the Pacific', 'Wakayama Prefecture',
       "Nuku'alofa", 'Saint-Benoît',
       'South Island, near Karitane north of Dunedin', 'Rocha',
       'Anzoategui', 'Cook Islands', 'Tamil Nadu', 'Taveuni',
       'Rio de Janeiro', 'Nueva Esparta', 'Southland',
       'North Pacific coast', 'Caroline Islands', 'Cheshire',
       'KwaZulu-Natal between Port Edward and Port St Johns',
       'Milne Bay Province', 'Rayong Province', 'New Brunswick',
       'Miyako Island', 'Alaska', 'Minerva Reef', 'Madang Province',
       'Worcestershire', 'Phang nga Province', 'Alinglaplap Atoll',
       'Ralik Chain', "L' Etang Salé-les-Bains", 'Rio Grande de Norte',
       'Southern Japan', 'Cap Vert Peninsula', 'Berry Islands',
       'Transvaal', 'Gaza', 'Miyako', 'Chatham Islands ',
       'South Sinai, Gulf of Aqaba', 'Missouri', 'Saint-Paul ',
       'Vava\x92u', 'Mississippi', 'Clearwater Bay', 'New Territories',
       'Aichi Prefecture', 'Saint-Denis', 'Banaadir Region',
       'La Libertad', 'Costa Blanca', 'Walkers Cay', 'Tongapatu Group',
       'Maranhão', 'Saint-Joseph', 'Antarctic Ocean', 'Ehime Prefecture',
       'La Saline-les-Bains', 'Ligurian Sea', "L'Etang-Salé",
       'Kowloon Peninsula', 'Port Shelter', 'Sainte-Marie',
       'Great Exuma Island', 'Sainte-Suzanne', 'Tuscany',
       'Tyrrhenian Sea', 'Valpariso Province', 'Saint-Louis',
       'Florida Straits', 'Cádiz', 'Sicily', 'Saint-Philippe', 'Chungnam',
       'Eronogo Region', 'Coquimbo', "Grand'Anse", "St. Mary's Parish",
       'Lamu Archipelago', 'Los Vilos', 'Madeira Islands',
       'Ralik Archipelago', 'Reggio Calabria Province', 'Florida ',
       'Upolu Island', 'Istria County', 'Coast Province',
       'Inhambe Province', 'Namonuito Atoll', 'Eastern Caroline Islands',
       'Western Caroline Islands ', 'St. Andrew Parish', 'Limpopo River',
       'Clarendon', 'Magdalena Department', 'Gulf Province',
       'New Ireland Province', 'Liguria', 'Hamilton', 'Out Islands',
       'Mugla Province', 'Veracruz', 'Bay of Maputo',
       'Duke of York Islands', 'Primorje-Gorski Kotar County ',
       'Taranto province', 'Northern Taiwan',
       'Admiralty Islands, Manus Province',
       "250 miles southwest of O'ahu, Hawaii", 'West coast', 'East Sepik',
       'Bimini Islands', 'Near Bougainville ', 'Western Caroline Islands',
       'Bougainville ', 'Victoria ', 'Okayama Prefecture', 'San Blas',
       'New Britain', 'Lau Group', 'Vita Levu', 'Vanua Levu',
       'Puntarenas Province', 'Lomaloma, Lau',
       'South Coast, East New Britain', ' Lau Province', 'Ysabel Island',
       'Santo Domingo', 'San Blas coast', 'Thessaly',
       'Lomaiviti  Island Group', 'Grand Turk Island',
       'Off coast of West Africa', 'Sharon', 'Northern District',
       'New Ireland Province, Bismarck Archipelago', 'Madang',
       'Guadalcanal Province', '10ºS, 142ºE', 'Kwajalein Atoll',
       'Western Luzon Island', 'Shefa Province',
       '25 km off the coast of Iran & 483km from mouth of Persian Gulf',
       'Venice Province', 'Sandaun Province', 'Anatolia', 'Adriatic Sea',
       'East New Britain Province', 'Wake Island ', '19S, 178?E',
       'Pennsylvania', 'Roncador Bank', 'Connecticut',
       'In the English Channel ', 'Unknown, treated at Wick, SCOTLAND',
       'San Blas Islands', 'Paget', 'Casamance', 'Masbate',
       'Lomaiviti Province', 'Kadavu', 'Leyte Island', 'Istria',
       'Guyamas', 'Mindanao', ' Kikori River mouth', 'Tutuila Island',
       'Guerrrero', 'West New Britain Province', 'Cat Cay',
       'Primorje-Gorski Kotar County', 'Between Hawaii & Wake Island',
       'Taipei Hsien', 'Morobe Province', 'Viti Levu',
       'Estuaire Province', 'Near Dakar, Cap Vert Peninsula',
       'Tyrrenian Sea', 'St. Thomas Bay', 'Madeira',
       '1000 miles west of Hawaii', 'Izo Islands',
       ' Primorje-Gorski Kotar County', 'Rhode Island', 'Aden',
       'New Ireland, Bismarck Archipelago', 'Wake Island', 'Isle of Man',
       'Slovenia', 'South shore ', 'Buenos Aires Province', 'Nova Scotia',
       'Gulf of Panama', 'Karun River', 'Genoa  Province',
       'Abau Sub District, Central Province', 'Red Sea State',
       'Port Louis Province', 'Bay of Maputu', 'Kingston Parish',
       'Salerno', 'Salerno Province', 'Corfu Island', 'Taranto',
       ' La Libertad', 'Sago Prefecture', 'Calabria',
       'Shatt-al-Arab River', 'Tamaulipas', 'Attica', 'Adana Province',
       'Khuzestan Province', 'Dar-es-Salaam ', 'Near the Fiji Islands',
       '40 miles south of Naples ', 'Makora-Ulawa Province',
       'Off coast of Ecuador', 'Trelawney Province', 'In Convoy OB 274',
       'Panama Bay ', 'Torres Strait ', 'North China', 'Basrah City',
       'Queensland ', 'Argyll', 'Colon Province', 'Makira-Uluwa Province',
       'Elqui Province', 'Istanbul', 'Havana Province',
       'Barlavento Islands', 'Viti Levu Island', 'Bay of Fundy', 'Manila',
       'Cienfuegos Province', 'Valencia', 'Salinas Bay',
       'Golfo di Genova in the Ligurian Sea', 'South of the Equator ',
       'Valencia ', 'Isle of Wight', 'Vancouver',
       '2 to 3 miles off Taboguilla Island, Pacific Ocean', 'Dorset',
       'Demerara County', 'Lucy', 'East Yorkshire', 'Cape Haitien',
       'Turtle Bogue', '60 miles north of San Domingo in the West Indies',
       'Gran Canaria', 'Apolima Strait', 'Zadar County', 'Essequibo',
       'Lagos ', 'Málaga ', 'Colón Province', 'Andalucia',
       'South Atlantic Ocean', 'Galicia', 'Gulf of Suez', 'Hong Kong',
       'Oaxaca', 'Harare Province', 'Westmoreland Parish', 'Java',
       ' Nusa Tenggara', 'Villa Clara Province', 'Rio San Juan',
       'Mediterranean Sea', 'Zamboanga del Sur Province',
       'Southern Cyprus', 'Western Viscayas', 'Imperia Province',
       'St Michael Parish', 'Moluccas', 'Provence', 'Rangoon',
       'Bay of Bengal', 'Bayelsa State', 'South Island?',
       'Woodlark Islands', 'Munxar Reef', 'Gujarat', 'Cortés',
       'West Bengal', 'Andaman Islands', 'East Java', 'Strait of Messina',
       'Cyclades archipelago', 'Gilbert Islands', 'Newfoundland',
       '22ºN, 88ºE', 'Hoogly River', 'Veracruz ', 'Alpes Maritime',
       'Eastern Catalona', 'Foveaux Strait', 'Conakry Region', 'Malaga',
       'Norfolk', 'Corfu', 'Vera Cruz', 'Matanzas Province ',
       'Sanma Province', "35º39 : 165º8'", 'CUBA', 'Western Area ',
       'Maharashtra', 'Southwest coast', 'Bocas del Toro Province',
       'Malaita Province', 'South Korea', 'Island of Volos',
       'North Carolina '], dtype=object)

In [46]:
data.Area = data.Area.str.strip(' ')

In [47]:
data.Area.unique()

array(['California', 'Georgia', 'Hawaii', 'New South Wales', 'Colima',
       'Pernambuco', 'Florida', 'Queensland', 'South Carolina',
       'Cornwall', 'Eastern Cape Province', 'Hua Hin', 'Cocos Island',
       'Western Australia', 'Alifu Alifu Atoll', 'Western Cape Province',
       'New Providence', 'Alagoas', 'Victoria', 'KwaZulu-Natal',
       'Boi Island, Victoria', 'Galapagos Islands', 'Fernando de Noronha',
       'Sepang', 'Holquin Province', 'Pamplemousses', 'South Australia',
       'North Island', 'Canary Islands', 'Westerm Australia',
       'Shizuoka Prefecture', 'Texas', 'Massachusetts',
       'Red Sea Protectorate', 'New Providence District',
       'Ascension Island', 'Majorca', 'Washington', 'Tabasco',
       'Ibiza Island', 'South Devon', 'Sharjah,', 'Baja California Sur',
       'Saint-Leu', 'South Island', 'Luzon Island', 'Bali', 'Tuamotos',
       'Oregon', 'North Province', 'New Providence Island',
       'Alicante Province', 'Kochi Prefecture', 'Tasmania',
       'Abaco Islands', 'North Carolina', 'Suez', 'Grand Terre',
       'Santa Catarina State', 'South Province', 'Altagracia Province',
       'Balneário Camboriú', 'Fujairah Emirate', 'Grand Canary Island',
       'Inhambane Province', 'Phuket', 'Guanacaste',
       'Grand Bahama Island', 'Le Port', 'Rangiroa',
       'Saint-Gilles-les-Bains', 'Bora Bora', 'Sinaloa',
       'Central Tuamotu', 'd\x92Étang-Salé', 'Granada', 'Moorea',
       'Alabama', 'Catalonia', 'Maryland', 'Alicante', 'Louisiana',
       'Delaware', 'Atsumi peninsula', 'Wallis and Futuna',
       'Society Islands', 'Okinawa Prefecture', 'New Jersey',
       'Southern District', 'Exuma Islands', 'Saint-Paul',
       'Santa Cruz Island', 'Saint-Gilles', 'Quintana Roo', 'Tuamotus',
       'Eleuthera', 'St. Catherine', 'Palawan', 'Mercury Islands',
       'Delta', "Vava'u", 'Inner Hebrides', 'Sardinia', 'Guerrero',
       'Saint-Benoit', 'Antofagasta Province', 'Taitung', 'Santa Elena',
       'East New Britain', 'Bois-Blanc', 'Moray', 'Samaná Province',
       'Central Province', 'Primorsky Krai',
       'Peter the Great Bay, Khasan, Primorsky Krai',
       'Telyakovsky Bay, Khasan,  Primorsky Krai', 'Praslin', 'Sucre',
       'Middle Caicos', 'Caicos Bank', 'San Andrés archipelago', 'Kedah',
       'Vitu Levu', 'Loyalty Islands', 'Saint Gilles', 'West End',
       'South Sinai Peninsula', 'Maine', 'Virginia', 'Jeju Province',
       'New York', 'Binh Dinh Province', 'Antsiranana Province',
       'Sinai Peninsula', 'Off Vanua Levu', 'Rio Grande Do Sul', 'Dubai',
       'Western Province', 'Torres Strait', 'Eastern Province',
       'Eastern Cape  Province', 'Maputo Province', 'Bocas', 'Fife',
       'Devon', 'Makira-Ulawa Province', 'Mombasa', 'St. Johns Reef',
       'Off Green Island', 'North Region', 'Batangas province',
       'Strait of Malacca', 'Puerto Rico', 'Guantanamo Province',
       'Red Sea', 'Batanes Provine', 'Luzon', 'Northern Territory',
       'Split-Dalmatia Count,', 'North Devon', 'US Virgin Islands',
       'San Carlos', 'Sussex', 'Bahia', 'Guerro', 'Yasawa Islands',
       'Northern Bahamas', 'Baja California', 'Marovo Lagoon',
       'Territory of Cocos  Islands', 'Oslo Fjord', 'Kent', 'Cook islans',
       'Saint-Pierre', 'Andros Islands', 'Guam', 'Western Area',
       'Simpson Bay', 'East Wall', 'Shanghai', 'Malampa Province',
       "South Ch'ungch'ong Province", 'New Mexico',
       'Santiago de Cuba Province', 'Camaguey Province',
       'Conservatória District', 'Kuril Islands in the Pacific',
       'Wakayama Prefecture', "Nuku'alofa", 'Saint-Benoît',
       'South Island, near Karitane north of Dunedin', 'Rocha',
       'Anzoategui', 'Cook Islands', 'Tamil Nadu', 'Taveuni',
       'Rio de Janeiro', 'Nueva Esparta', 'Southland',
       'North Pacific coast', 'Caroline Islands', 'Cheshire',
       'KwaZulu-Natal between Port Edward and Port St Johns',
       'Milne Bay Province', 'Rayong Province', 'New Brunswick',
       'Miyako Island', 'Alaska', 'Minerva Reef', 'Madang Province',
       'Worcestershire', 'Phang nga Province', 'Alinglaplap Atoll',
       'Ralik Chain', "L' Etang Salé-les-Bains", 'Rio Grande de Norte',
       'Southern Japan', 'Cap Vert Peninsula', 'Berry Islands',
       'Transvaal', 'Gaza', 'Miyako', 'Chatham Islands',
       'South Sinai, Gulf of Aqaba', 'Missouri', 'Vava\x92u',
       'Mississippi', 'Clearwater Bay', 'New Territories',
       'Aichi Prefecture', 'Saint-Denis', 'Banaadir Region',
       'La Libertad', 'Costa Blanca', 'Walkers Cay', 'Tongapatu Group',
       'Maranhão', 'Saint-Joseph', 'Antarctic Ocean', 'Ehime Prefecture',
       'La Saline-les-Bains', 'Ligurian Sea', "L'Etang-Salé",
       'Kowloon Peninsula', 'Port Shelter', 'Sainte-Marie',
       'Great Exuma Island', 'Sainte-Suzanne', 'Tuscany',
       'Tyrrhenian Sea', 'Valpariso Province', 'Saint-Louis',
       'Florida Straits', 'Cádiz', 'Sicily', 'Saint-Philippe', 'Chungnam',
       'Eronogo Region', 'Coquimbo', "Grand'Anse", "St. Mary's Parish",
       'Lamu Archipelago', 'Los Vilos', 'Madeira Islands',
       'Ralik Archipelago', 'Reggio Calabria Province', 'Upolu Island',
       'Istria County', 'Coast Province', 'Inhambe Province',
       'Namonuito Atoll', 'Eastern Caroline Islands',
       'Western Caroline Islands', 'St. Andrew Parish', 'Limpopo River',
       'Clarendon', 'Magdalena Department', 'Gulf Province',
       'New Ireland Province', 'Liguria', 'Hamilton', 'Out Islands',
       'Mugla Province', 'Veracruz', 'Bay of Maputo',
       'Duke of York Islands', 'Primorje-Gorski Kotar County',
       'Taranto province', 'Northern Taiwan',
       'Admiralty Islands, Manus Province',
       "250 miles southwest of O'ahu, Hawaii", 'West coast', 'East Sepik',
       'Bimini Islands', 'Near Bougainville', 'Bougainville',
       'Okayama Prefecture', 'San Blas', 'New Britain', 'Lau Group',
       'Vita Levu', 'Vanua Levu', 'Puntarenas Province', 'Lomaloma, Lau',
       'South Coast, East New Britain', 'Lau Province', 'Ysabel Island',
       'Santo Domingo', 'San Blas coast', 'Thessaly',
       'Lomaiviti  Island Group', 'Grand Turk Island',
       'Off coast of West Africa', 'Sharon', 'Northern District',
       'New Ireland Province, Bismarck Archipelago', 'Madang',
       'Guadalcanal Province', '10ºS, 142ºE', 'Kwajalein Atoll',
       'Western Luzon Island', 'Shefa Province',
       '25 km off the coast of Iran & 483km from mouth of Persian Gulf',
       'Venice Province', 'Sandaun Province', 'Anatolia', 'Adriatic Sea',
       'East New Britain Province', 'Wake Island', '19S, 178?E',
       'Pennsylvania', 'Roncador Bank', 'Connecticut',
       'In the English Channel', 'Unknown, treated at Wick, SCOTLAND',
       'San Blas Islands', 'Paget', 'Casamance', 'Masbate',
       'Lomaiviti Province', 'Kadavu', 'Leyte Island', 'Istria',
       'Guyamas', 'Mindanao', 'Kikori River mouth', 'Tutuila Island',
       'Guerrrero', 'West New Britain Province', 'Cat Cay',
       'Between Hawaii & Wake Island', 'Taipei Hsien', 'Morobe Province',
       'Viti Levu', 'Estuaire Province', 'Near Dakar, Cap Vert Peninsula',
       'Tyrrenian Sea', 'St. Thomas Bay', 'Madeira',
       '1000 miles west of Hawaii', 'Izo Islands', 'Rhode Island', 'Aden',
       'New Ireland, Bismarck Archipelago', 'Isle of Man', 'Slovenia',
       'South shore', 'Buenos Aires Province', 'Nova Scotia',
       'Gulf of Panama', 'Karun River', 'Genoa  Province',
       'Abau Sub District, Central Province', 'Red Sea State',
       'Port Louis Province', 'Bay of Maputu', 'Kingston Parish',
       'Salerno', 'Salerno Province', 'Corfu Island', 'Taranto',
       'Sago Prefecture', 'Calabria', 'Shatt-al-Arab River', 'Tamaulipas',
       'Attica', 'Adana Province', 'Khuzestan Province', 'Dar-es-Salaam',
       'Near the Fiji Islands', '40 miles south of Naples',
       'Makora-Ulawa Province', 'Off coast of Ecuador',
       'Trelawney Province', 'In Convoy OB 274', 'Panama Bay',
       'North China', 'Basrah City', 'Argyll', 'Colon Province',
       'Makira-Uluwa Province', 'Elqui Province', 'Istanbul',
       'Havana Province', 'Barlavento Islands', 'Viti Levu Island',
       'Bay of Fundy', 'Manila', 'Cienfuegos Province', 'Valencia',
       'Salinas Bay', 'Golfo di Genova in the Ligurian Sea',
       'South of the Equator', 'Isle of Wight', 'Vancouver',
       '2 to 3 miles off Taboguilla Island, Pacific Ocean', 'Dorset',
       'Demerara County', 'Lucy', 'East Yorkshire', 'Cape Haitien',
       'Turtle Bogue', '60 miles north of San Domingo in the West Indies',
       'Gran Canaria', 'Apolima Strait', 'Zadar County', 'Essequibo',
       'Lagos', 'Málaga', 'Colón Province', 'Andalucia',
       'South Atlantic Ocean', 'Galicia', 'Gulf of Suez', 'Hong Kong',
       'Oaxaca', 'Harare Province', 'Westmoreland Parish', 'Java',
       'Nusa Tenggara', 'Villa Clara Province', 'Rio San Juan',
       'Mediterranean Sea', 'Zamboanga del Sur Province',
       'Southern Cyprus', 'Western Viscayas', 'Imperia Province',
       'St Michael Parish', 'Moluccas', 'Provence', 'Rangoon',
       'Bay of Bengal', 'Bayelsa State', 'South Island?',
       'Woodlark Islands', 'Munxar Reef', 'Gujarat', 'Cortés',
       'West Bengal', 'Andaman Islands', 'East Java', 'Strait of Messina',
       'Cyclades archipelago', 'Gilbert Islands', 'Newfoundland',
       '22ºN, 88ºE', 'Hoogly River', 'Alpes Maritime', 'Eastern Catalona',
       'Foveaux Strait', 'Conakry Region', 'Malaga', 'Norfolk', 'Corfu',
       'Vera Cruz', 'Matanzas Province', 'Sanma Province',
       "35º39 : 165º8'", 'CUBA', 'Maharashtra', 'Southwest coast',
       'Bocas del Toro Province', 'Malaita Province', 'South Korea',
       'Island of Volos'], dtype=object)

In [48]:
#!pip install pycountry

In [49]:
#!pip install geopy

In [50]:
import pycountry

In [51]:
pycountry.countries.search_fuzzy('BRAZIL')

[Country(alpha_2='BR', alpha_3='BRA', name='Brazil', numeric='076', official_name='Federative Republic of Brazil')]

In [52]:
from geopy.geocoders import Nominatim

In [53]:
geolocator = Nominatim(user_agent='your_search')

In [55]:
def geolocate(country):
    try:
            # Geolocate the center of the country
            loc = geolocator.geocode(country)
            # And return latitude and longitude 
            return [loc.latitude, loc.longitude]
        # Otherwise
    except:
            # Return missing value
            return np.nan

In [56]:
list_coord3 = []
for i in tqdm(data['Country']):
    d = geolocate(i)
    list_coord3.append(d)

100%|██████████████████████████████████████████████████████████████████████████████| 4116/4116 [34:18<00:00,  2.00it/s]

In [57]:
list_coord3

[[39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [22.5000485, -100.0000375],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [52.5310214, -1.2649062],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [14.8971921, 100.83273],
 [9.5773243, -83.82371114343024],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [4.7064352, 73.3287853],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [14.8971921, 100.83273],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [24.7736546, -78.0000547],
 [-10.3333333, -53.2],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [-1.3397668, -79.3666965],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [4.5693754, 102.2656823],
 [9.5773243, -83.82371114343024],
 [9.5773243, -83.82371114343024],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [23.0131338, -80.8328748],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-20.2759451, 57.5703566],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-41.5000831, 172.8344077],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [36.5748441, 139.2394179],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-41.5000831, 172.8344077],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [26.2540493, 29.2675469],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [-15.9656162, -5.702145010209923],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [22.5000485, -100.0000375],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [54.7023545, -3.2765753],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [24.0002488, 53.9994829],
 [-24.7761086, 134.755],
 [22.5000485, -100.0000375],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [-41.5000831, 172.8344077],
 [-15.9656162, -5.702145010209923],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [12.7503486, 122.7312101],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-10.3333333, -53.2],
 [-28.8166236, 24.991639],
 [-10.3333333, -53.2],
 [-24.7761086, 134.755],
 [-2.4833826, 117.8902853],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [-16.03442485, -146.0490931059517],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-20.454288599999998, 164.55660583077983],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [36.5748441, 139.2394179],
 [-24.7761086, 134.755],
 [24.7736546, -78.0000547],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [26.2540493, 29.2675469],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-41.5000831, 172.8344077],
 [-2.4833826, 117.8902853],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [-16.03442485, -146.0490931059517],
 [-16.03442485, -146.0490931059517],
 [39.7837304, -100.4458825],
 [-20.454288599999998, 164.55660583077983],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [-20.454288599999998, 164.55660583077983],
 [-20.454288599999998, 164.55660583077983],
 [19.28131815, -70.035906834967],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [24.0002488, 53.9994829],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [-28.8166236, 24.991639],
 [-1.3397668, -79.3666965],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-19.302233, 34.9144977],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-19.302233, 34.9144977],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-19.302233, 34.9144977],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [14.8971921, 100.83273],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [9.5773243, -83.82371114343024],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [-24.7761086, 134.755],
 [22.5000485, -100.0000375],
 [-16.03442485, -146.0490931059517],
 [-21.130737949999997, 55.536480112992315],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [24.7736546, -78.0000547],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.3260685, -4.8379791],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.3260685, -4.8379791],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [36.5748441, 139.2394179],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [46.603354, 1.8883335],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [-24.7761086, 134.755],
 [-41.5000831, 172.8344077],
 [-24.7761086, 134.755],
 [-41.5000831, 172.8344077],
 [36.5748441, 139.2394179],
 [-20.454288599999998, 164.55660583077983],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-21.130737949999997, 55.536480112992315],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [31.5313113, 34.8667654],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [24.7736546, -78.0000547],
 [-10.3333333, -53.2],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-1.3397668, -79.3666965],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [22.5000485, -100.0000375],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [-28.8166236, 24.991639],
 [-28.8166236, 24.991639],
 [18.1850507, -77.3947693],
 [-24.7761086, 134.755],
 [12.7503486, 122.7312101],
 [-28.8166236, 24.991639],
 [-41.5000831, 172.8344077],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-41.5000831, 172.8344077],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [22.5000485, -100.0000375],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [9.6000359, 7.9999721],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-19.9160819, -175.2026424],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [56.7861112, -4.1140518],
 [-24.7761086, 134.755],
 [-10.3333333, -53.2],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-16.03442485, -146.0490931059517],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [42.6384261, 12.674297],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [22.5000485, -100.0000375],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-41.5000831, 172.8344077],
 [-24.7761086, 134.755],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [-31.7613365, -71.3187697],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [23.9739374, 120.9820179],
 [-24.7761086, 134.755],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [-1.3397668, -79.3666965],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [-24.7761086, 134.755],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [-2.4833826, 117.8902853],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-5.6816069, 144.2489081],
 [-10.3333333, -53.2],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [56.7861112, -4.1140518],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [19.28131815, -70.035906834967],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-5.6816069, 144.2489081],
 [-24.7761086, 134.755],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [64.6863136, 97.7453061],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [64.6863136, 97.7453061],
 [39.7837304, -100.4458825],
 [64.6863136, 97.7453061],
 [-16.03442485, -146.0490931059517],
 [-4.6574977, 55.4540146],
 [39.7837304, -100.4458825],
 [-4.6574977, 55.4540146],
 [39.7837304, -100.4458825],
 [-28.8166236, 24.991639],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],
 [39.7837304, -100.4458825],
 [24.7736546, -78.0000547],
 [39.7837304, -100.4458825],
 [39.7837304, -100.4458825],
 [-21.130737949999997, 55.536480112992315],

In [58]:
data['Coordenates'] = list_coord3

In [59]:
data['Coordenates'] = data['Coordenates'].astype(str)

In [60]:
data.query('Coordenates == "nan"')

Empty DataFrame
Columns: [Month, Year, Type, Country, Area, Location, Activity, Sex , Injury, Fatal (Y/N), Coordenates]
Index: []

In [61]:
data.Coordenates = data.Coordenates.str.rstrip(']').str.strip('[')

In [62]:
data.reset_index(drop=True, inplace=True)

In [63]:
data['Longtitude'] = data.Coordenates.str.split(',').str.get(-1)

In [64]:
data.Coordenates = data.Coordenates.str.split(',').str.get(0)

In [65]:
data.rename(columns={'Coordenates':'Latitude'}, inplace=True)

In [66]:
data

,Month,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N),Latitude,Longtitude
0,Jun,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,"No injury to occupant, outrigger canoe and pad...",N,39.7837304,-100.4458825
1,Jun,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,Minor injury to left thigh,N,39.7837304,-100.4458825
2,Jun,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,Injury to left lower leg from surfboard skeg,N,39.7837304,-100.4458825
3,Jun,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,Minor injury to lower leg,N,-24.7761086,134.755
4,Jun,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N,22.5000485,-100.0000375
...,...,...,...,...,...,...,...,...,...,...,...,...
4111,May,1965,Unprovoked,GREECE,Island of Volos,Eastern shore,Swimming,F,FATAL,Y,38.9953683,21.9877132
4112,Apr,1959,Unprovoked,BERMUDA,Paget,Paget Parish,Spearfishing,M,Shoulder abraded by skin of shark,N,32.3018217,-64.7603583
4113,Jul,1916,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,"""Lost leg""",N,39.7837304,-100.4458825
4114,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,M,"FATAL, body not recovered but shark was caught...",Y,-28.8166236,24.991639
4115,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y,-28.8166236,24.991639

In [67]:
data['Hemisphere'] = np.where(data.Latitude.str.contains('-'), 'South', 'North')

In [68]:
data.query('Latitude =="nan"')

Empty DataFrame
Columns: [Month, Year, Type, Country, Area, Location, Activity, Sex , Injury, Fatal (Y/N), Latitude, Longtitude, Hemisphere]
Index: []

In [69]:
data.tail(10)

,Month,Year,Type,Country,Area,Location,Activity,Sex,Injury,Fatal (Y/N),Latitude,Longtitude,Hemisphere
4106,Feb,1998,Unprovoked,SOLOMON ISLANDS,Malaita Province,Waibana Passage,Diving,M,Lacerations to hands and knee,N,-8.7053941,159.1070693851845,South
4107,May,1996,Unprovoked,KOREA,South Korea,Cheju Island,Diving,F,"FATAL, injured while diving, then shark bit her",Y,36.638392,127.6961188,North
4108,Mar,1995,Unprovoked,FRENCH POLYNESIA,Tuamotus,Rangiroa,Fishing,M,"Speared a shark, fell overboard and another sh...",N,-16.03442485,-146.0490931059517,South
4109,Aug,1987,Provoked,VANUATU,Malampa Province,"Hokai, Malakula",Attempting to drive shark from area,M,Speared shark broke outrigger of canoe throwin...,N,-16.5255069,168.1069154,South
4110,Jan,1967,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Keiskamma River mouth,Crossing river on a raft,M,"FATAL, leg severed",Y,-28.8166236,24.991639,South
4111,May,1965,Unprovoked,GREECE,Island of Volos,Eastern shore,Swimming,F,FATAL,Y,38.9953683,21.9877132,North
4112,Apr,1959,Unprovoked,BERMUDA,Paget,Paget Parish,Spearfishing,M,Shoulder abraded by skin of shark,N,32.3018217,-64.7603583,North
4113,Jul,1916,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,"""Lost leg""",N,39.7837304,-100.4458825,North
4114,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,M,"FATAL, body not recovered but shark was caught...",Y,-28.8166236,24.991639,South
4115,Jul,1913,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,M,"FATAL, leg stripped of flesh",Y,-28.8166236,24.991639,South